In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.models import Sequential

In [ ]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
num_classes=10
input_shape=(28,28,1)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((60000, 28, 28), (10000, 28, 28), (60000,), (10000,))

In [ ]:
y_train[0]

5

In [ ]:
x_train=x_train.astype("float32")/255
x_test=x_test.astype("float32")/255

In [ ]:
x_train.shape

(60000, 28, 28)

In [ ]:
x_train=np.expand_dims(x_train, -1)
x_test=np.expand_dims(x_test, -1)

In [ ]:
x_train.shape

(60000, 28, 28, 1)

In [ ]:
y_train=keras.utils.to_categorical(y_train, num_classes)
y_test=keras.utils.to_categorical(y_test, num_classes)

In [ ]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [ ]:
model=keras.Sequential()
model.add(keras.Input(shape=input_shape))
model.add(layers.Conv2D(10, kernel_size=(5,5), activation="relu"))
model.add(layers.MaxPooling2D(pool_size=(2,2)))
model.add(layers.Conv2D(20, kernel_size=(5,5), activation="relu"))
model.add(layers.MaxPooling2D(pool_size=(2,2)))
model.add(layers.Dropout(0.25))
model.add(layers.Flatten())
model.add(layers.Dense(50, activation="relu"))
model.add(layers.Dense(10, activation="relu"))
model.add(layers.Dense(num_classes, activation="softmax"))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 24, 24, 10)          │             260 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 12, 12, 10)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 8, 8, 20)            │           5,020 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 4, 4, 20)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 4, 4, 20)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 320)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 50)                  │          16,050 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │             510 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 10)                  │             110 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 21,950 (85.74 KB)

 Trainable params: 21,950 (85.74 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(
    loss="categorical_crossentropy", # Changed from sparse_categorical_crossentropy
    optimizer=keras.optimizers.Adadelta(),
    metrics=["accuracy"])


In [ ]:
batch_size=128
epochs=10
model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1,validation_data=(x_test, y_test))

Epoch 1/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 29s 62ms/step - accuracy: 0.1160 - loss: 2.2799 - val_accuracy: 0.1601 - val_loss: 2.2632
Epoch 2/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 40s 61ms/step - accuracy: 0.1224 - loss: 2.2715 - val_accuracy: 0.1653 - val_loss: 2.2546
Epoch 3/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 41s 61ms/step - accuracy: 0.1275 - loss: 2.2630 - val_accuracy: 0.1674 - val_loss: 2.2445
Epoch 4/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 41s 60ms/step - accuracy: 0.1318 - loss: 2.2542 - val_accuracy: 0.1681 - val_loss: 2.2328
Epoch 5/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 30s 63ms/step - accuracy: 0.1348 - loss: 2.2449 - val_accuracy: 0.1708 - val_loss: 2.2199
Epoch 6/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 28s 60ms/step - accuracy: 0.1396 - loss: 2.2349 - val_accuracy: 0.1746 - val_loss: 2.2062
Epoch 7/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 41s 61ms/step - accuracy: 0.1389 - loss: 2.2240 - val_accuracy: 0.1783 - val_loss: 2.1915
Epoch 8/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 41s 62ms/step - accuracy: 0.1431 - loss: 2.2143 - 

In [ ]:
import numpy as np
predict_prob=model.predict(x_test)
predict_classes=np.argmax(predict_prob,axis=1)
print(predict_classes)
print(y_test)


313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step
[3 5 5 ... 5 5 5]
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
predict_prob

array([[0.10310631, 0.09843757, 0.07152019, ..., 0.12821388, 0.09312355,
        0.10374243],
       [0.08790611, 0.11550649, 0.12950826, ..., 0.0791794 , 0.11982536,
        0.06115235],
       [0.09286824, 0.10862374, 0.11245815, ..., 0.09746934, 0.11104503,
        0.08158936],
       ...,
       [0.0880496 , 0.09062865, 0.09592157, ..., 0.09848925, 0.09602001,
        0.09333987],
       [0.09413572, 0.10062623, 0.1075647 , ..., 0.10214581, 0.10766476,
        0.08004882],
       [0.08743608, 0.09127784, 0.08772114, ..., 0.06556241, 0.09994309,
        0.06196923]], dtype=float32)

In [ ]:
loss,acc=model.evaluate(x_test, y_test)
print("Test Accuracy",acc)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.1929 - loss: 2.1518
Test Accuracy 0.1972000002861023
