In [ ]:
import tensorflow as tf
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Flatten


In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [ ]:
type(x_train), x_train.shape, x_test.shape, y_train.shape, y_test.shape

(numpy.ndarray, (60000, 28, 28), (10000, 28, 28), (60000,), (10000,))

In [ ]:
num_classes=10

In [ ]:
model=Sequential()
model.add(Flatten(input_shape=(28,28)))
model.add(Dense(140, activation='relu'))
model.add(Dense(240, activation='relu'))
model.add(Dense(140, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

In [ ]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ flatten_2 (Flatten)                  │ (None, 784)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 140)                 │         109,900 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ (None, 240)                 │          33,840 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 140)                 │          33,740 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 10)                  │           1,410 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 178,890 (698.79 KB)

 Trainable params: 178,890 (698.79 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer=keras.optimizers.Adadelta(),
    metrics=["accuracy"])

In [ ]:
batch_size=128
epochs=20
model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1,validation_data=(x_test, y_test))

Epoch 1/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.7364 - loss: 4.2856 - val_accuracy: 0.7385 - val_loss: 4.1417
Epoch 2/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.7479 - loss: 4.0525 - val_accuracy: 0.7465 - val_loss: 3.9600
Epoch 3/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.7540 - loss: 3.9369 - val_accuracy: 0.7556 - val_loss: 3.8008
Epoch 4/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.7628 - loss: 3.7193 - val_accuracy: 0.7612 - val_loss: 3.6578
Epoch 5/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.7709 - loss: 3.5679 - val_accuracy: 0.7673 - val_loss: 3.5274
Epoch 6/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.7756 - loss: 3.4389 - val_accuracy: 0.7738 - val_loss: 3.4093
Epoch 7/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.7830 - loss: 3.2835 - val_accuracy: 0.7795 - val_loss: 3.2993
Epoch 8/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.7864 - loss: 3.2503 - val_accuracy: 0.

In [ ]:
import numpy as np
predict_prob=model.predict(x_test)
predict_classes=np.argmax(predict_prob,axis=1)
print(predict_classes)
print(y_test)


313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[7 2 1 ... 9 5 6]
[7 2 1 ... 4 5 6]


In [ ]:
predict_prob

array([[1.4372409e-28, 2.5385214e-33, 1.2221248e-32, ..., 9.9999994e-01,
        4.3761216e-28, 4.0596408e-11],
       [6.2159864e-17, 1.0693934e-25, 9.9999994e-01, ..., 1.9978559e-21,
        1.9154296e-27, 0.0000000e+00],
       [7.1924441e-28, 9.9999994e-01, 1.3929636e-20, ..., 1.2526143e-19,
        1.2394985e-14, 7.0964413e-25],
       ...,
       [2.3908652e-38, 0.0000000e+00, 0.0000000e+00, ..., 3.3704035e-21,
        1.1295835e-17, 9.1904676e-01],
       [8.5116164e-11, 3.9420723e-25, 3.5674254e-20, ..., 2.6418975e-28,
        1.2378689e-13, 1.3148633e-27],
       [9.7321760e-35, 0.0000000e+00, 3.0630966e-38, ..., 0.0000000e+00,
        1.7083239e-19, 0.0000000e+00]], dtype=float32)

In [ ]:
loss,acc=model.evaluate(x_test, y_test)
print("Test Accuracy",acc)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7923 - loss: 2.7435
Test Accuracy 0.8215000033378601
